# Paste your Bot Token here
SLACK_BOT_TOKEN = "https://hooks.slack.com/services/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"

# This is the password for the manager page
MANAGER_PASSWORD = "Learnapp.123"

# Paste each of your Channel IDs here
WRITER_SLACK_CHANNEL_ID = "C0..."
GRAPHIC_SLACK_CHANNEL_ID = "C09L65S88C9"
EDITOR_SLACK_CHANNEL_ID = "C0..."
REINDEX_SLACK_CHANNEL_ID = "C0..."
SOCIAL_SLACK_CHANNEL_ID = "C0..."
COMPANY_WIDE_SLACK_CHANNEL_ID = "C0..."
